### ISSUE TITLE
Downloading from northwestern  doesn't work

### ISSUE THREAD

**Issue by pmatos** [greghendershott/travis-racket#22]
My builds started failing because travis racket tries to download from northwestern and this doesn't seem to work anymore.

```
$ cat travis-racket/install-racket.sh | bash
Checking installer
Downloading http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh to ./racket-HEAD.sh:
```
this times out.

**Comment by pmatos** [comment]
Pull request #23 should fix this.

**Comment by greghendershott** [comment]
Could you double check on Slack? ISTR switching to Utah but being advised
to use NW.

**Comment by greghendershott** [comment]
I sent that from phone. Got to real computer and asked on Slack myself. It seems that was a (rare) outage and we should stick with Northwestern?

**Comment by pmatos** [comment]
You're correct. Thanks for confirming this.
