### ISSUE TITLE
Racket 5 installers get SSL errors when installing packages

### ISSUE THREAD

**Issue by clacke** [greghendershott/travis-racket#31]
```
$ git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
[ . . . ]
$ cat ../travis-racket/install-racket.sh | bash
Checking installer
Downloading https://mirror.racket-lang.org/installers/5.3.2/racket/racket-5.3.2-bin-x86_64-linux-debian-squeeze.sh to ./racket-5.3.2.sh:
[ . . . ]
$ export PATH="${RACKET_DIR}/bin:${PATH}"
$ raco pkg install --deps search-auto ../graph
The following packages are listed as dependencies, but are not currently installed,
so they will be automatically installed:
	base data-lib math-lib 
ssl-connect: connect failed (error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure)
```

I'm guessing this is because those Rackets are built with an OpenSSL that is too old to talk to https://pkgs.racket-lang.org/ .

**Comment by greghendershott** [comment]
Thanks for reporting. Another issue is #9. As a result, I put 5.x under `allow_failures` -- [example](https://github.com/greghendershott/sha/blob/master/.travis.yml#L52-L54) -- in the few projects where I still support 5.x. But that's very few. 5.x is quite old by now.

**Comment by clacke** [comment]
Yeah, that's what `graph` does too. Hypothetically it still supports 5.3.2, but verifying that in Travis is hard.

**Comment by greghendershott** [comment]
I'm going to close because I think there's no to-do, but if you disagree please feel free to reopen.
