### ISSUE TITLE
RELEASE version not working

### ISSUE THREAD

**Issue by pmatos** [greghendershott/travis-racket#32]
It seems that at the moment the `RELEASE` value for `RACKET_VERSION` is not working. I am getting:
```
$ export RACKET_VERSION="RELEASE"
$ export RACKET_DIR="racket"
$ git clone https://github.com/greghendershott/travis-racket.git
Cloning into 'travis-racket'...
$ cat travis-racket/install-racket.sh | bash
Checking installer
Downloading https://pre-release.racket-lang.org/installers/racket-current-x86_64-linux.sh to ./racket-RELEASE.sh:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:25 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:27 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:28 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0
100  4776    0  4776    0     0    151      0 --:--:--  0:00:31 --:--:--  1125
100  4776    0  4776    0     0    151      0 --:--:--  0:00:31 --:--:--  1471
Making ./racket-RELEASE.sh executable:
Running ./racket-RELEASE.sh to install Racket:
./racket-RELEASE.sh: line 1: syntax error near unexpected token `newline'
./racket-RELEASE.sh: line 1: `<!DOCTYPE html>'
ERROR: Job failed: exit code 1
```

**Comment by greghendershott** [comment]
Maybe you saw this on Slack: `mirror.racket-lang.org` was unresponsive much of Tuesday, and even more of Wednesday. This affected humans using the download button on `downloads.racket-lang.org`, too. Apparently a machine named `winooski` at NEU was filing to response. Late yesterday, Matthew said they changed that to use Utah. So I changed `DL_BASE` here to Utah, too.

I kind of feel like there's no point in trying to fix PRE-RELEASE until things settle down there. But if you disagree, can figure out a good URL, and want to submit a PR (or even just tell me what URL to use so I can change it myself), that would be wonderful.

**Comment by pmatos** [comment]
Oh. I noticed the mirroring issue but I failed to connect the dots with this. But I don't quite understand how that affects RELEASE. But no worries about it now then. It's bed time here... I just really need something that does not fail for CI. I will think of something tomorrow. Thanks. 

On 11 April 2019 22:37:01 CEST, Greg Hendershott <notifications@github.com> wrote:
>Maybe you saw this on Slack: `mirror.racket-lang.org` was unresponsive
>much of Tuesday, and even more of Wednesday. This affected humans using
>the download button on `downloads.racket-lang.org`, too. Apparently a
>machine named `winooski` at NEU was filing to response. Late yesterday,
>Matthew said they changed that to use Utah. So I changed `DL_BASE` here
>to Utah, too.
>
>I kind of feel like there's no point in trying to fix PRE-RELEASE until
>things settle down there. But if you disagree, can figure out a good
>URL, and want to submit a PR (or even just tell me what URL to use so I
>can change it myself), that would be wonderful.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/greghendershott/travis-racket/issues/32#issuecomment-482301913

--
Paulo Matos

**Comment by greghendershott** [comment]
Ah I forgot the time zone. I'll see if I can figure it out myself; maybe I can have it working again when you wake up.

If they change the preferred location back to NEU or whatever, later, maybe you could help me undo these work-arounds, then. :smile:

**Comment by greghendershott** [comment]
From [Slack](https://racket.slack.com/archives/C06V96CKX/p1555016056580500) it seems that this is temporarily unavailable, while the 7.3 release is being prepared.

You might want to update your `.travis.yml` to add `RELEASE` under `allow_failures`, as is done in [this section of the example](https://github.com/greghendershott/travis-racket/blob/master/.travis.yml#L38-L48).

**Comment by greghendershott** [comment]
I'm going to close because I think there's no to-do, but if you disagree please feel free to reopen.
